//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiXamarin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugador
    {
        public int jugador_id { get; set; }
        public int equipo_id { get; set; }
        public string jugador_nombre { get; set; }
        public string jugador_foto { get; set; }
        public Nullable<System.DateTime> jugador_fecha { get; set; }
        public string jugador_equipo { get; set; }
        public string jugador_posicion { get; set; }
        public int jugador_edad { get; set; }
        public Nullable<int> jugador_goles { get; set; }
        public string jugador_division { get; set; }
        public Nullable<int> jugador_numero { get; set; }
    
        public virtual Equipo Equipo { get; set; }
    }
}
